/**
 * Generates a `content/blurMap.ts` file containing tiny base64 blur dataURLs
 * for every image in:
 *   public/images/objects/*.jpg
 *   public/images/services/*.jpg
 *   public/images/home/*.jpg
 *
 * The map is keyed by the public URL of each image (e.g. `/images/objects/01.jpg`),
 * so consumers can do `blurMap[item.images[0].src]` without any IO at runtime.
 *
 * Re-run with `npm run gen:blur` whenever images change.
 */
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { getPlaiceholder } from 'plaiceholder'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const PUBLIC = path.join(ROOT, 'public')

const DIRS = [
  'images/objects',
  'images/services',
  'images/home',
] as const

async function listImages(rel: string): Promise<string[]> {
  const abs = path.join(PUBLIC, rel)
  let entries: string[] = []
  try {
    entries = await fs.readdir(abs)
  } catch {
    return []
  }
  return entries
    .filter((name) => /\.(jpe?g|png|webp|avif)$/i.test(name))
    .map((name) => path.posix.join('/', rel, name))
}

async function computeBlur(publicUrl: string): Promise<string> {
  const abs = path.join(PUBLIC, publicUrl.replace(/^\/+/, ''))
  const buffer = await fs.readFile(abs)
  const { base64 } = await getPlaiceholder(buffer, { size: 10 })
  return base64
}

async function main() {
  const allUrls = (
    await Promise.all(DIRS.map((d) => listImages(d)))
  ).flat()

  const entries: [string, string][] = []
  for (const url of allUrls) {
    try {
      const dataUrl = await computeBlur(url)
      entries.push([url, dataUrl])
      console.log('✓', url)
    } catch (err) {
      console.warn('✗', url, err instanceof Error ? err.message : err)
    }
  }

  entries.sort(([a], [b]) => a.localeCompare(b))

  const body = entries
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n')

  const file = `// Auto-generated by scripts/gen-blur.ts. Do not edit by hand.
// Run \`npm run gen:blur\` to regenerate.

export const blurMap: Record<string, string> = {
${body}
}
`
  const outPath = path.join(ROOT, 'content', 'blurMap.ts')
  await fs.writeFile(outPath, file, 'utf8')
  console.log(`\nWrote ${entries.length} entries → content/blurMap.ts`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
